<?xml version="1.0" encoding="utf-8"?><Database Name="adventureDataZad4" Class="DataBaseTablesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\adventureDataZad4.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="Zad4Database.Properties.Settings" SettingsPropertyName="adventureDataZad4ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="Production.ProductCategory" Member="ProductCategory">
    <Type Name="ProductCategory">
      <Column Name="ProductCategoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="rowguid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>